### PR TITLE
Remove 'skip_add_to_invoice' from api interface.

### PR DESCRIPTION
**Pull request by mtbottle**
This PR is to remove the `skip_add_to_invoice` from API as it is no longer supported.

### CODE REVIEW

**Comment by mtbottle** [comment]
Similar to https://github.com/laterpay/laterpay-client-python/pull/70, it might make sense to raise a warning rather than removing the field altogether.

**Comment by jmcodingde** [comment]
Nice to see some activity here! Thanks for your work :-)
Could you just add a test for the deprecation notice to make coveralls happy?

**Comment by mtbottle** [comment]
Yep, was working on it! :) I'm just a bit concerned about the way I'm logging the deprecation notice. Is `console.log` fine? Or is there something more better?

**Comment by jmcodingde** [comment]
How about `console.warn` for the deprecation notice?

**Comment by mtbottle** [comment]
Changed it to use `console.warn` :+1:

**Pull request merged**
